In [67]:
print("Hello, Abhinay")

Hello, Abhinay

In [68]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"], index=["a","b","c"], dtype="int16")

In [69]:
df.shape

(3, 3)

In [70]:
df

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

Loading data from Files in DataFrame

In [71]:
coffeeShop = pd.read_csv('https://raw.githubusercontent.com/Abhinay-05/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')
coffeeShop

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [72]:
results = pd.read_parquet('./data/results.parquet')

In [73]:
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name="results")
olympics_data.head(5)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [74]:
bioSet = pd.read_csv('./data/bios.csv')

In [75]:
noc = pd.read_csv('./data/noc_regions.csv')

Accessing data with Python

In [76]:
# coffeeShop.sample(5)
# coffeeShop.loc[row, column] it takes names
# coffeeShop.iloc[:, [0]] it takes indices
# coffeeShop.loc[0:, "Day"]
# coffeeShop.at[0, "Units Sold"] = 24
coffeeShop.sort_values(["Coffee Type", "Units Sold"], ascending=[1,0])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
2     Tuesday    Espresso          30
0      Monday    Espresso          25
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [77]:
bioSet.loc[(bioSet["height_cm"] > 210) & (bioSet["born_country"]=="USA"), ["name", "height_cm"]]

                      name  height_cm
5681          Walt Bellamy      211.0
5781        Tommy Burleson      223.0
5894            Mel Counts      213.0
6106       Marc Freiberger      211.0
6281        Darrall Imhoff      211.0
6379            Joe Kleine      211.0
6393            Jon Koncak      213.0
6442    Christian Laettner      211.0
6615          Tom McMillen      212.0
6722      Shaquille O'Neal      216.0
6937        David Robinson      216.0
7012       Daniel Santiago      213.0
112319         Chris Kaman      213.0
112366       Dwight Howard      211.0
118573     Al-Farouq Aminu      211.0
123850      Tyson Chandler      216.0
132188    Domantas Sabonis      211.0
133332      DeAndre Jordan      211.0
142044       Jahlil Okafor      211.0
142930          Mike Tobey      213.0
143712        JaVale McGee      213.0

In [78]:
bioSet[bioSet['name'].str.contains("Abhina")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
92335,93075,Abhinav Bindra,1982-09-28,Dehradun,Uttar Pradesh,IND,India,173.0,70.0,NaN

Adding/Removing data

In [79]:
coffeeShop["Price"] = np.where(coffeeShop["Coffee Type"] == "Espresso", 3.99, 5.99)
coffeeShop

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   3.99
1      Monday       Latte          15   5.99
2     Tuesday    Espresso          30   3.99
3     Tuesday       Latte          20   5.99
4   Wednesday    Espresso          35   3.99
5   Wednesday       Latte          25   5.99
6    Thursday    Espresso          40   3.99
7    Thursday       Latte          30   5.99
8      Friday    Espresso          45   3.99
9      Friday       Latte          35   5.99
10   Saturday    Espresso          45   3.99
11   Saturday       Latte          35   5.99
12     Sunday    Espresso          45   3.99
13     Sunday       Latte          35   5.99

In [80]:
coffeeShop["Revenue"] = coffeeShop["Units Sold"] * coffeeShop["Price"]
coffeeShop["Profit"] = coffeeShop["Revenue"] * 0.07

coffeeShop

          Day Coffee Type  Units Sold  Price  Revenue   Profit
0      Monday    Espresso          25   3.99    99.75   6.9825
1      Monday       Latte          15   5.99    89.85   6.2895
2     Tuesday    Espresso          30   3.99   119.70   8.3790
3     Tuesday       Latte          20   5.99   119.80   8.3860
4   Wednesday    Espresso          35   3.99   139.65   9.7755
5   Wednesday       Latte          25   5.99   149.75  10.4825
6    Thursday    Espresso          40   3.99   159.60  11.1720
7    Thursday       Latte          30   5.99   179.70  12.5790
8      Friday    Espresso          45   3.99   179.55  12.5685
9      Friday       Latte          35   5.99   209.65  14.6755
10   Saturday    Espresso          45   3.99   179.55  12.5685
11   Saturday       Latte          35   5.99   209.65  14.6755
12     Sunday    Espresso          45   3.99   179.55  12.5685
13     Sunday       Latte          35   5.99   209.65  14.6755

In [81]:

bioSet['born_date'] = pd.to_datetime(bioSet['born_date'], errors='coerce')
bioSet['born_year'] = bioSet['born_date'].dt.year
# create new CSV without any added index
# bioSet.to_csv('./data/bioSet.csv', index=False)
bioSet.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878.0

In [82]:
bioSet['height_category'] = bioSet['height_cm'].apply(
    lambda x: "Nan" if pd.isna(x) else("Short" if x<165 else("Average" if x<180 else "Tall"))
)
bioSet.sort_values('height_cm').tail()
bioSet.sort_values('height_cm').tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_year,height_category
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,1995.0,Nan
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,1989.0,Nan
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,1927.0,Nan
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,1998.0,Nan
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913.0,Nan

In [83]:
def categorize_athelete(row):
    if row['height_cm'] == pd.isna(row['height_cm']) or row['weight_kg'] == pd.isna(row['weight_kg']):
        return "NaN"
    elif row['height_cm'] < 175 and row['weight_kg'] < 70:
        return "Light Weight"
    elif row['height_cm'] < 185 and row['weight_kg'] <= 80:
        return "Middle Weight"
    else:
        return "Heavy Weight"
    
# bioSet['Category'] = bioSet.apply(categorize_athelete, axis=1)    
bioSet['height_cm'] == "NaN"

0         False
1         False
2         False
3         False
4         False
          ...
145495    False
145496    False
145497    False
145498    False
145499    False
Name: height_cm, Length: 145500, dtype: bool

Merging and Concatenating data

In [84]:
nocs = pd.read_csv('./data/noc_regions.csv')

In [85]:
bios_new=pd.merge(bioSet, nocs, left_on='born_country', right_on='NOC', how='inner')

In [86]:
bios_new.rename(columns={'region':'born_country_full'}, inplace=True)

In [87]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name                NOC_x born_country_full
4              Albert Canet               France                UK
14               Guy Forget               France           Morocco
32          Helen Aitchison        Great Britain                UK
33        Geraldine Beamish        Great Britain                UK
34             Dora Boothby        Great Britain                UK
...                     ...                  ...               ...
110630         Shakeel John  Trinidad and Tobago          Trinidad
110632   Landysh Falyakhova                  ROC            Russia
110634    Polina Luchnikova                  ROC            Russia
110635  Valeriya Merkusheva                  ROC            Russia
110636      Yuliya Smirnova                  ROC            Russia

[38349 rows x 3 columns]

In [88]:
usa = bioSet[bioSet['born_country'] == 'USA'].copy()
gbr = bioSet[bioSet['born_country'] == 'GBR'].copy()

In [89]:
gbr.count()

athlete_id         5792
name               5792
born_date          5792
born_city          5792
born_region        5792
born_country       5792
NOC                5792
height_cm          3608
weight_kg          3424
died_date          2443
born_year          5792
height_category    5792
dtype: int64

In [90]:
new_df = pd.concat([usa,gbr])

In [91]:
new_df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_year,height_category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,1967.0,Average
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,1968.0,Average
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,1973.0,Short
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,1897.0,Nan
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,1975.0,Average
...,...,...,...,...,...,...,...,...,...,...,...,...
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,1983.0,Nan
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,1993.0,Nan
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,2001.0,Tall
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,1992.0,Nan
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,1993.0,Nan

In [92]:
combined_df = pd.merge(results, bioSet, on='athlete_id', how='left')

In [93]:
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_year,height_category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0,Nan
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0,Nan
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0,Nan
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0,Nan
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,...,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN,2001.0,Tall
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,...,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN,1998.0,Nan
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,...,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,2000.0,Nan
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,...,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,2000.0,Nan
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,...,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN,1994.0,Nan

In [94]:
coffeeShop['Units Sold'].interpolate()

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

Aggregate Data

In [96]:
bioSet[bioSet['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [97]:
coffeeShop.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [100]:
pivot = coffeeShop.pivot(columns='Coffee Type', index='Day')
pivot

            Units Sold          Price        Revenue           Profit
Coffee Type   Espresso Latte Espresso Latte Espresso   Latte Espresso    Latte
Day
Friday              45    35     3.99  5.99   179.55  209.65  12.5685  14.6755
Monday              25    15     3.99  5.99    99.75   89.85   6.9825   6.2895
Saturday            45    35     3.99  5.99   179.55  209.65  12.5685  14.6755
Sunday              45    35     3.99  5.99   179.55  209.65  12.5685  14.6755
Thursday            40    30     3.99  5.99   159.60  179.70  11.1720  12.5790
Tuesday             30    20     3.99  5.99   119.70  119.80   8.3790   8.3860
Wednesday           35    25     3.99  5.99   139.65  149.75   9.7755  10.4825

In [101]:
pivot.sum(axis=1)

Day
Friday       506.424
Monday       252.852
Saturday     506.424
Sunday       506.424
Thursday     443.031
Tuesday      316.245
Wednesday    379.638
dtype: float64

In [107]:
bioSet.groupby(bioSet['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

Advanced Functionality

In [109]:
# coffeeShop['Revenue'] = coffeeShop['Units Sold']*coffeeShop['Price']
coffeeShop

          Day Coffee Type  Units Sold  Price  Revenue   Profit
0      Monday    Espresso          25   3.99    99.75   6.9825
1      Monday       Latte          15   5.99    89.85   6.2895
2     Tuesday    Espresso          30   3.99   119.70   8.3790
3     Tuesday       Latte          20   5.99   119.80   8.3860
4   Wednesday    Espresso          35   3.99   139.65   9.7755
5   Wednesday       Latte          25   5.99   149.75  10.4825
6    Thursday    Espresso          40   3.99   159.60  11.1720
7    Thursday       Latte          30   5.99   179.70  12.5790
8      Friday    Espresso          45   3.99   179.55  12.5685
9      Friday       Latte          35   5.99   209.65  14.6755
10   Saturday    Espresso          45   3.99   179.55  12.5685
11   Saturday       Latte          35   5.99   209.65  14.6755
12     Sunday    Espresso          45   3.99   179.55  12.5685
13     Sunday       Latte          35   5.99   209.65  14.6755